server:
  port: 9000

spring:
  servlet:
    multipart:
      enabled: true
      location: /Users/v.sultanyarov/Desktop/tmp #TODO временное
      max-file-size: 5MB
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    password: secret
    username: myuser
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/auth_db
    locations: classpath:db/migration
    password: secret
    user: myuser
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000
        endpoint:
          oidc:
            user-info-uri: /api/v1/user_info
