services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=auth_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
        RABBITMQ_DEFAULT_PASS: secret
        RABBITMQ_DEFAULT_USER: myuser
    ports:
      - '5672:5672'
      - '15672:15672'
